charAt(index);
charCodeAt(index);
slice(beginIndex, endIndex);
substring(indexStart, indexEnd);
split(separator, limit);
// concat(str1, str2, ...);
includes(searchString, position);
endsWith(searchString, length);
indexOf(searchValue, fromIndex);
lastIndexOf(searchValue, fromIndex);
startsWith(searchString, position);
repeat(count);
replace(searchValue, newValue);
localeCompare(compareString, locales, options);
toLowerCase();
toUpperCase();
toString();
valueOf();
padStart(targetLength, padString);
padEnd(targetLength, padString);
trim();
trimStart() / trimLeft();
trimEnd() / trimRight();
match(regexp);
search(regexp);
